import testPhoto from '@/assets/images/test-student.jpg';

const testStudents = [
  {
    id: 0,
    activeStatus: true,
    photo: testPhoto,
    name: 'Иван Иванов',
    studentSubject: 'Английский',
    studentSubjectLevel: 'B2',
    email: 'eR7zg@example.com',
    phone: '+7 (999) 999-99-99',
    homeWorkDone: 3,
    homeWorkArrowUp: 0,
    homeWorkToDo: 2,
  },
  {
    id: 1,
    activeStatus: true,
    photo: testPhoto,
    name: 'Петр Петров',
    studentSubject: 'Английский',
    studentSubjectLevel: 'A1',
    email: 'eR7zg@example.com',
    phone: '+7 (999) 999-99-99',
    homeWorkDone: 3,
    homeWorkArrowUp: 0,
    homeWorkToDo: 2,
  },
  {
    id: 2,
    activeStatus: true,
    photo: testPhoto,
    name: 'Денис Денисов',
    studentSubject: 'Английский',
    studentSubjectLevel: 'B2',
    email: 'eR7zg@example.com',
    phone: '+7 (999) 999-99-99',
    homeWorkDone: 3,
    homeWorkArrowUp: 0,
    homeWorkToDo: 2,
  },
  {
    id: 3,
    activeStatus: true,
    photo: testPhoto,
    name: 'Евгения Евгеньевна',
    studentSubject: 'Английский',
    studentSubjectLevel: 'A2',
    email: 'eR7zg@example.com',
    phone: '+7 (999) 999-99-99',
    homeWorkDone: 3,
    homeWorkArrowUp: 0,
    homeWorkToDo: 2,
  },
  {
    id: 4,
    activeStatus: false,
    photo: testPhoto,
    name: 'Иван Иванов',
    studentSubject: 'Китайский',
    studentSubjectLevel: 'B2',
    email: 'eR7zg@example.com',
    phone: '+7 (999) 999-99-99',
    homeWorkDone: 3,
    homeWorkArrowUp: 0,
    homeWorkToDo: 2,
  },
  {
    id: 5,
    activeStatus: false,
    photo: testPhoto,
    name: 'Семен Семенович',
    studentSubject: 'Английский',
    studentSubjectLevel: 'C1',
    email: 'eR7zg@example.com',
    phone: '+7 (999) 999-99-99',
    homeWorkDone: 3,
    homeWorkArrowUp: 0,
    homeWorkToDo: 2,
  },
];

export default testStudents;
