import testPhoto from '@/assets/images/test-student.jpg'

const testStudents = [
  {
    id: 0,
    activeStatus: true,
    photo: testPhoto,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    studentSubject: 'Английский',
    studentSubjectLevel: 'B2',
    email: 'eR7zg@example.com',
    phone: '+7 (999) 999-99-99',
    homeWorkDone: 3,
    homeWorkArrowUp: 0,
    homeWorkToDo: 2,
  },
  {
    id: 1,
    activeStatus: true,
    photo: testPhoto,
    firstName: 'Петр',
    lastName: 'Петров',
    patronymic: 'Петрович',
    studentSubject: 'Английский',
    studentSubjectLevel: 'A1',
    email: 'eR7zg@example.com',
    phone: '+7 (999) 999-99-99',
    homeWorkDone: 3,
    homeWorkArrowUp: 0,
    homeWorkToDo: 2,
  },
  {
    id: 2,
    activeStatus: true,
    photo: testPhoto,
    firstName: 'Денис',
    lastName: 'Денисов',
    patronymic: '',
    studentSubject: 'Английский',
    studentSubjectLevel: 'B2',
    email: 'eR7zg@example.com',
    phone: '+7 (999) 999-99-99',
    homeWorkDone: 3,
    homeWorkArrowUp: 0,
    homeWorkToDo: 2,
  },
  {
    id: 3,
    activeStatus: true,
    photo: testPhoto,
    firstName: 'Петр',
    lastName: 'Петров',
    patronymic: 'Петрович',
    studentSubject: 'Английский',
    studentSubjectLevel: 'A2',
    email: 'eR7zg@example.com',
    phone: '+7 (999) 999-99-99',
    homeWorkDone: 3,
    homeWorkArrowUp: 0,
    homeWorkToDo: 2,
  },
  {
    id: 4,
    activeStatus: false,
    photo: testPhoto,
    firstName: 'Иван',
    lastName: 'Иванов',
    patronymic: 'Иванович',
    studentSubject: 'Китайский',
    studentSubjectLevel: 'B2',
    email: 'eR7zg@example.com',
    phone: '+7 (999) 999-99-99',
    homeWorkDone: 3,
    homeWorkArrowUp: 0,
    homeWorkToDo: 2,
  },
  {
    id: 5,
    activeStatus: false,
    photo: testPhoto,
    firstName: 'Семен',
    lastName: 'Семенов',
    patronymic: '',
    studentSubject: 'Английский',
    studentSubjectLevel: 'C1',
    email: 'eR7zg@example.com',
    phone: '+7 (999) 999-99-99',
    homeWorkDone: 3,
    homeWorkArrowUp: 0,
    homeWorkToDo: 2,
  },
]

export default testStudents
