export enum validateType {
  email = 'email',
  firstName = 'firstName',
  lastName = 'lastName',
  patronymic = 'patronymic',
  phone = 'phone',
  password = 'password',
  confirmPassword = 'confirmPassword',
  currentPassword = 'currentPassword',
  userRole = 'userRole',
  policy = 'policy',
  subject = 'subject',
  feedbackMessage = 'feedbackMessage',
  level = 'level',
  storybook = 'storybook',
  sortBy = 'sortBy',
}
